# Real-Time Scheduling and Memory Lock limits for PipeWire & WirePlumber
@audio   -  rtprio     95
@audio   -  nice      -19
@audio   -  memlock    unlimited
yurko    -  rtprio     95
yurko    -  nice      -19
yurko    -  memlock    unlimited
